#---------------Modified common costmap----------------#

#Robot's Boundaries
footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
footprint_padding: 0.01  
#robot_radius: 0.2 
max_obstacle_height:  0.6     # the arm is mounted on top of the robot

#GeneralParams
robot_base_frame: base_link   
update_frequency: 5.0
publish_frequency: 2.0   #the frequency in Hz for the map to be publish display information
transform_tolerance: 0.5 #the amount of time in seconds to wait for a transform to become available before failing the update 
width: 10.0              #the width of the costmap in meters
height: 10.0             #the height of the costmap in meters 
resolution: 0.05         #meters/cell

#Marking&Clearing
obstacle_range: 3.0      #robot will only update its map with information about obstacles that are within 3.0 meters 
raytrace_range: 3.0      #robot will attempt to clear out space in front of it up to 3.0 meters away given a sensor reading

obstacle_layer:
  enabled: true

  #ObstacleCostmapPlugin
  track_unknown_space: true         #true means each pixel has one of 3 states: lethal obstacle, free, or unknown
  footprint_clearing_enabled: true  #default: true  
  combination_method: 1             #default: 1, the cell cost is the maximum of the cell cost and the obstacle cost
 
  #VoxelCostmapPlugin
  z_resolution: 0.1         #The z resolution of the map in meters/cell.
  z_voxels: 20              #The number of voxels in each vertical column, the height of the grid is z_resolution * z_voxels
  unknown_threshold: 10     #The number of unknown cells allowed in a column considered to be "known"
  mark_threshold: 0         #The maximum number of marked cells allowed in a column considered to be "free"
  publish_voxel_map: true   #Whether or not to publish the underlying voxel grid for visualization purposes

  #ObservationSources
  observation_sources: laser_scan_sensor  #The name of the observation source
  laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
  
inflation_layer:
  enabled: true

  cost_scaling_factor: 3.0   #the cost of the inflation layer is 3 times the cost of the obstacle layer 
  inflation_radius: 1.0      #the robot will avoid obstacles within 0.5 meters from its center

static_layer:
  enabled: true