global_costmap:

  global_frame: /map                # the frame in which the costmap should be built
  static_map: true                  # determines whether or not the costmap should initialize itself based on a map
  rolling_window: false             # determines whether or not the costmap should be centered on the robot
  width: 100.0                      #the width of the costmap in meters
  height: 100.0                     #the height of the costmap in meters 
  plugins:
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}



