local_costmap:

  global_frame: odom    
  static_map: false
  rolling_window: true

  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}




